# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: '1.2'
_src_path: https://github.com/m-birke/python-project-template.git
package_name: dygo
project_description: Dynamic Gooey from config files
project_name: dygo
